CREATE DATABASE BAITHI

CREATE TABLE HANG(
	MAHANG char(4) NOT NULL,
	TENHANG varchar(20),
	NUOCSX varchar(20),
	CHUHANG varchar(40)
	CONSTRAINT PK_HANG PRIMARY KEY(MAHANG)
)

CREATE TABLE KHACHHANG(
	MAKH char(5) NOT NULL,
	TENKH varchar(20),
	NGSINH smalldatetime,
	GIOITINH varchar(5),
	NGDK smalldatetime,
	CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)	

CREATE TABLE DONGXE(
	MADONG char(4) NOT NULL,
	MAHANG char(4),
	TENDONG varchar(20),
	LOAINL varchar(5),
	LOAIPIN varchar(20),
	NGRM smalldatetime,
	CONSTRAINT PK_DX PRIMARY KEY(MADONG)
)

CREATE TABLE XE(
	MAXE char(4) NOT NULL,
	MADONG char(4) NOT NULL,
	MAKH char(5) NOT NULL,
	BIENSO varchar(20),
	NGMUA smalldatetime,
	NGBD smalldatetime,
	SOCHO tinyint,
	CONSTRAINT PK_XE PRIMARY KEY(MAXE)
)

ALTER TABLE DONGXE ADD CONSTRAINT FR_DONGXE FOREIGN KEY(MAHANG) REFERENCES HANG(MAHANG)
ALTER TABLE XE ADD CONSTRAINT FR01_XE FOREIGN KEY(MADONG) REFERENCES DONGXE(MADONG)
ALTER TABLE XE ADD CONSTRAINT FR02_XE FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

SET DATEFORMAT dmy

--2
INSERT INTO HANG VALUES('H001','VinFast','Viet nam','Pham Nhat Vuong')
INSERT INTO HANG VALUES('H002','Dat bike','Viet nam','Nguyen Ba Canh Son')
INSERT INTO HANG VALUES('H003','Kia','Kia','Kim Cheol-ho')
SELECT * FROM HANG


INSERT INTO KHACHHANG VALUES('KH001','Phuong My Chi','20/06/2003','Nu','25/05/2020')
INSERT INTO KHACHHANG VALUES('KH002','Huynh Hong Loan','13/09/1998','Nu','24/06/2020')
INSERT INTO KHACHHANG VALUES('KH003','Nguyen Minh Son','15/06/1989','Nam','13/07/2021')
SELECT * FROM KHACHHANG

INSERT INTO DONGXE VALUES('D001','H001','Klara','Dien','Lithium-ion','26/12/2020')
INSERT INTO DONGXE VALUES('D002','H002','Dat bikeweaver++','Dien','Lithium-ion','04/12/2022')
INSERT INTO DONGXE VALUES('D003','H003','Sorento','Xang','null','14/09/2020')
	
UPDATE DONGXE SET NGRM='26/12/2020' WHERE MADONG='D001'

INSERT INTO XE VALUES('X001','D001','KH001','51-T1 063.25','20/05/2022','20/07/2022', 2)
INSERT INTO XE VALUES('X002','D002','KH002','30V 123.08 ','19/06/2022','15/08/2022', 2)
INSERT INTO XE VALUES('X003','D003','KH003','51-T2 010.04','13/07/2022','20/08/2022', 4)
SELECT * FROM XE

--3
ALTER TABLE DONGXE ADD CONSTRAINT CHECK_LOAIPIN CHECK(YEAR(NGRM)<2020 AND LOAIPIN<>'Lithium-ion' OR YEAR(NGRM)>=2020)

--4
GO
CREATE TRIGGER I_U_X on XE
FOR insert,update
AS
BEGIN
	IF(EXISTS(SELECT * FROM inserted,DONGXE WHERE inserted.MADONG=DONGXE.MADONG AND YEAR(inserted.NGBD)<2020
	AND DONGXE.LOAIPIN='Lithium-ion'))
	BEGIN
		PRINT 'loi'
		ROLLBACK
	END
END


--5
SELECT D.MADONG,D.TENDONG FROM DONGXE D,XE X,KHACHHANG K WHERE D.MADONG=X.MADONG AND X.MAKH=K.MAKH
AND K.GIOITINH='Nu' AND YEAR(X.NGBD)=2022 AND MONTH(X.NGBD)IN(1,2,3) ORDER BY D.NGRM

--6
SELECT G.MAHANG,G.TENHANG FROM HANG G,DONGXE D,XE X WHERE G.MAHANG=D.MAHANG AND D.MADONG=X.MADONG AND YEAR(X.NGBD)=2022 AND X.SOCHO = 2 GROUP BY G.MAHANG,G.TENHANG  HAVING COUNT(MAXE) =
(SELECT TOP(1) COUNT(MAXE) AS SOLUONG FROM XE X,DONGXE D WHERE X.MADONG=D.MADONG AND YEAR(X.NGBD)=2022 AND X.SOCHO = 2 GROUP BY  D.MADONG,D.MAHANG ORDER BY SOLUONG DESC)

--7
SELECT K.MAKH,K.TENKH FROM KHACHHANG K,DONGXE D,XE X WHERE K.MAKH=X.MAKH AND X.MADONG=D.MADONG AND D.LOAINL='Xang' AND
NOT EXISTS
(SELECT A.MAKH,A.TENKH FROM KHACHHANG A,DONGXE B,XE C WHERE A.MAKH=C.MAKH AND B.MADONG=C.MADONG AND B.LOAINL<>'Xang' AND A.MAKH=K.MAKH)
--8
SELECT MAKH FROM KHACHHANG K WHERE NOT EXISTS
(SELECT * FROM DONGXE D,HANG g WHERE D.MAHANG=G.MAHANG AND G.NUOCSX='Viet nam' AND NOT EXISTS
(SELECT * FROM XE X WHERE X.MADONG=D.MADONG AND K.MAKH=X.MAKH))



